import { Client } from '../utils/types';

export const CLIENTS : Client[]= [
    { id: 1, name: 'Zim Gas LTD', abbreviation:'' ,img: '/clients_logo/zim_gas.png' },
    { id: 2, name: 'Maxwell International Ventures LTD', abbreviation: 'SPDC' },
    { id: 3, name: 'Selai Gas Station LTD', abbreviation: 'CVX', img: '/clients_logo/selai.png' },
    { id: 4, name: 'Total Energies', abbreviation: 'TTE', img: '/clients_logo/total-energy.jpeg' },
    { id: 5, name: 'ExxonMobil', abbreviation: 'XOM', img: '/clients_logo/exxon-mobil.png' },
    { id: 6, name: 'Ameogo Gas Accurate Grace LTD', abbreviation: 'SEP' },
    { id: 7, name: 'Oando Energy', abbreviation: 'OAN', img: '/clients_logo/oando.png' },
    { id: 8, name: 'Dangote', abbreviation: 'DNG', img: '/clients_logo/dangote.png' },
    { id: 9, name: 'Dobum Nigeria LTD', abbreviation: 'DNL' },
    { id: 10, name: 'Conoil', abbreviation: 'CON', img: '/clients_logo/conoil.png' },
    { id: 11, name: 'NIPCO', abbreviation: 'NPC' },
    { id: 12, name: 'Forte Oil', abbreviation: 'FTO', img: '/clients_logo/forteoil.png' },
    { id: 13, name: 'Emayh Nigeria LTD', abbreviation: 'ENL' },
    { id: 14, name: 'Hansreal Petroleum LTD', abbreviation: 'HPL' },
    { id: 15, name: 'Mikel Energy LTD', abbreviation: 'MEL' },
    { id: 16, name: 'Fowobi Nigeria Enterprises LTD', abbreviation: 'FNE' },
    { id: 17, name: 'Yerevan Oil and Gas LTD', abbreviation: 'YOG' },
    { id: 18, name: 'DPL Limited Bisfun Petroleum LTD', abbreviation: 'BISFUN' },
    { id: 19, name: 'Sedabuk Oil and Gas LTD', abbreviation: 'SOG' },
    { id: 20, name: 'Gate Link Oil and Gas LTD', abbreviation: 'GOG' },
    { id: 21, name: 'Wheel Oil LTD', abbreviation: 'FTO', img: '/clients_logo/wheeloil.png' },
    { id: 22, name: '247 Finance Investment LTD', abbreviation: '247' },
    { id: 23, name: 'Habod Gas Ltd', abbreviation: 'HGL' },
    { id: 24, name: 'City Gas Ltd', abbreviation: 'CGL', img: '/clients_logo/city-gas.jpeg' },
    { id: 25, name: 'Second Coming Nigeria Ltd', abbreviation: 'SCN' },
    { id: 26, name: 'NNPC', abbreviation: 'NNPC', img: '/clients_logo/nnpc.jpeg' },
    { id: 27, name: 'Crown Flour Mill LTD', abbreviation: 'CFM', img: '/clients_logo/crown-flour.png' },
    { id: 28, name: 'Placid LTD', abbreviation: 'PLACID' },
    { id: 29, name: 'Sweet Nutrition LTD', abbreviation: 'SNL', img: '/clients_logo/sweet-nutrition.jpeg' },
    { id: 30, name: 'Mohaz Oil and Gas LTD', abbreviation: 'MOG' },
    { id: 31, name: 'Mikano International LTD', abbreviation: 'MIL', img: '/clients_logo/mikano.png' },
    { id: 32, name: 'Ade Gas LTD', abbreviation: 'AGL' },
    { id: 33, name: 'Anchor Gas LTD', abbreviation: 'AGL' },
    { id: 34, name: 'Gunon Oil and Gas LTD', abbreviation: 'GOG' },
    { id: 35, name: 'VeeVee Products LTD', abbreviation: 'VPL' },
    { id: 36, name: 'Purechem Manfacturing LTD', abbreviation: 'PML', img: '/clients_logo/purechem.png' },
    { id: 37, name: 'AshKash Nigeria LTD', abbreviation: 'ANL' },
    { id: 38, name: 'Matrix Energy LTD', abbreviation: 'MEL', img: '/clients_logo/matrix.png' },
    { id: 39, name: '11 Plc', abbreviation: '11 PLC' },
    { id: 40, name: 'BHR Gas LTD', abbreviation: 'BGL', img: '/clients_logo/bhr.jpeg' },
    { id: 41, name: 'Petrocam Gas LTD', abbreviation: 'PGL', img: '/clients_logo/petrocam.jpeg' },
    { id: 42, name: 'Messers Maxwell International Ventures LTD', abbreviation: 'MMIV' },
    { id: 43, name: 'Mega Plastic LTD', abbreviation: 'MPL' },
    { id: 44, name: 'Gas Terminaling LTD', abbreviation: 'GTL', img: '/clients_logo/gas-terminaling.jpeg' },
    { id: 45, name: 'Elesther Energy LTD', abbreviation: 'EEL' },
    { id: 46, name: 'Crown Deluxe LTD', abbreviation: 'CDL' },
    { id: 47, name: 'Fatgbems LTD', abbreviation: 'FL', img: '/clients_logo/fatgbems.jpeg' },
    { id: 48, name: 'Biswal', abbreviation: 'BISWAL', img: '/clients_logo/biswal.png' },
  ];